In [1]:
import numpy as np
import scipy.linalg as linear

#QR Methods
def simpleQR(A, tol, maxIter=1e3):
    i = 0
    while i < maxIter and linear.norm(A.diagonal(-1))>tol:
        [Q,R] = linear.qr(A)
        A = R.dot(Q)
        i += 1
    return A,i

def shiftQRStep(A, tol):
    i = 0
    while A[-1,-2]>tol:
        shift = A[-1,-1]
        [Q,R] = linear.qr(A-shift*np.identity(len(A)))
        A = R.dot(Q)+shift*np.identity(len(A))
        i += 1
    return A,i

def shiftQR(A, tol, maxIter=1e3):
    i = 0
    A = linear.hessenberg(A)
    eigenvalues = []
    while i<maxIter and len(A)>1:
        [A,j] = shiftQRStep(A,tol)
        eigenvalues.append(A[-1,-1])
        A = A[:-1,:-1]
        i += j
    eigenvalues.append(A[0,0])
    return eigenvalues,i

In [2]:
A=np.array([[0,1,2],[1,0,1],[2,1,0]])
print("A")
print(A)

A
[[0 1 2]
 [1 0 1]
 [2 1 0]]


In [3]:
linear.eig(A)

(array([ 2.73205081+0.j, -2.00000000+0.j, -0.73205081+0.j]),
 array([[ -6.27963030e-01,  -7.07106781e-01,   3.25057584e-01],
        [ -4.59700843e-01,   1.64352863e-16,  -8.88073834e-01],
        [ -6.27963030e-01,   7.07106781e-01,   3.25057584e-01]]))

In [4]:
simpleQR(A,10**-10)

(array([[  2.73205081e+00,   7.76052179e-11,   4.52172420e-16],
        [  7.76065272e-11,  -2.00000000e+00,   3.46344160e-16],
        [  1.71922142e-45,  -3.32295778e-35,  -7.32050808e-01]]), 80)

In [5]:
shiftQRStep(A,10**-10)

(array([[ 0.8       , -1.79629248,  1.46059349],
        [-1.79629248, -0.13333333, -0.2981424 ],
        [ 1.46059349, -0.2981424 , -0.66666667]]), 1)

In [6]:
shiftQR(A,10**-10)

([-0.73205080756887753, -1.9999999999999998, 2.7320508075688763], 5)