In [1]:
import numpy as np
import scipy.linalg as linear

#Power Methods
def powerMethod(A, q, tol, maxIter=1e3):
    w = q/linear.norm(q)
    i = 0
    flag = 0
    while(i < maxIter and not flag):
        i += 1
        q = A.dot(w)
        l = w.dot(q)
        w = q/linear.norm(q)
        flag = linear.norm(A.dot(w)-l*w) <= tol*linear.norm(A.dot(w))
    return w,l,i

def inversePower(A, q, tol, maxIter=1e3):
    w = q/linear.norm(q)
    i = 0
    flag = 0
    while(i < maxIter and not flag):
        i += 1
        q = linear.solve(A,w)
        l = w.dot(q)
        w = q/linear.norm(q)
        flag = linear.norm(A.dot(w)-(1/l)*w) <= tol*linear.norm(A.dot(w))
    return w,1/l,i
        
def inversePowerShift(A, q, r, tol, maxIter=1e3):
    w = q/linear.norm(q)
    i = 0
    flag = 0
    while(i < maxIter and not flag):
        i += 1
        q = linear.solve(A-r*np.identity(len(A)),w)
        l = w.dot(q)
        w = q/linear.norm(q)
        flag = linear.norm(A.dot(w)-(1/l+r)*w) <= tol*linear.norm(A.dot(w))
    return w,(1/l+r),i

def inversePowerRayleigh(A, q, tol, maxIter=1e3): 
    w = q/linear.norm(q)
    l = w.dot(A.dot(w))
    i = 0
    flag = 0
    while(i < maxIter and not flag):
        i += 1
        #Agregar try-catch para matrix singular, terminar ejecucion
        q = linear.solve(A-l*np.identity(len(A)),w)
        w = q/linear.norm(q)
        l = w.dot(A.dot(w))
        flag = linear.norm(A.dot(w)-l*w) <= tol
    return w,l,i

In [2]:
A=np.array([[0,1,2],[1,0,1],[2,1,0]])
q=np.array([1,1,-1])
print(" A \t \t q")
print(A , '\t', q)

 A 	 	 q
[[0 1 2]
 [1 0 1]
 [2 1 0]] 	 [ 1  1 -1]


In [3]:
linear.eig(A)

(array([ 2.73205081+0.j, -2.00000000+0.j, -0.73205081+0.j]),
 array([[ -6.27963030e-01,  -7.07106781e-01,   3.25057584e-01],
        [ -4.59700843e-01,   1.64352863e-16,  -8.88073834e-01],
        [ -6.27963030e-01,   7.07106781e-01,   3.25057584e-01]]))

In [4]:
powerMethod(A,q,1e-11)

(array([ 0.62796303,  0.45970084,  0.62796303]), 2.7320508075688776, 87)

In [5]:
inversePower(A,q,1e-11)

(array([ 0.32505758, -0.88807383,  0.32505758]), -0.7320508075688773, 27)

In [6]:
inversePowerShift(A,q,2,1e-11)

(array([ 0.62796303,  0.45970084,  0.62796303]), 2.7320508075688772, 20)

In [7]:
inversePowerShift(A,q,-1.8,1e-11)

(array([ -7.07106781e-01,   6.81670459e-12,   7.07106781e-01]), -2.0, 15)

In [8]:
inversePowerShift(A,q,-0.6,1e-11)

(array([-0.32505758,  0.88807383, -0.32505758]), -0.73205080756887719, 12)

In [9]:
inversePowerRayleigh(A,q,1e-7)

(array([ -7.07106781e-01,   3.64072561e-13,   7.07106781e-01]), -2.0, 5)

In [10]:
inversePowerRayleigh(A,np.array([1,.7,1]),1e-7)

(array([ 0.62796303,  0.45970084,  0.62796303]), 2.7320508075688776, 2)

In [11]:
inversePowerRayleigh(A,np.array([3,-7,3]),1e-7)

(array([ 0.32505758, -0.88807383,  0.32505758]), -0.73205080756887719, 2)