In [1]:
import numpy as np
import scipy.linalg as linear

In [2]:
A=np.matrix('1 2 3;4 5 6;7 8 9') #preguntar pq no sirve con '2 1;1 2', tiene q ver con dim(eigenespacio(2))=2? o por A-2I ortogonal?

In [3]:
def simpleQR(A, eps):
    while linear.norm(A.diagonal(-1))>eps:
        [Q,R]=linear.qr(A)
        A=R.dot(Q)
    return A

In [4]:
simpleQR(A,10**-10)

array([[  1.61168440e+001,  -4.89897949e+000,  -5.06073432e-015],
       [  8.04476733e-011,  -1.11684397e+000,   1.20365131e-016],
       [  1.11271449e-164,  -2.13754610e-154,  -4.53828149e-016]])

In [5]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
def shiftQRStep(A,eps):
    while A[-1,-2]>eps:
        shift=A[-1,-1]
        [Q,R]=linear.qr(A-shift*np.identity(len(A)))
        A=R.dot(Q)+shift*np.identity(len(A))
    return A

In [7]:
shiftQRStep(A,10**-10)

array([[ -1.02922023e+00,  -3.00306721e-01,   4.70287598e+00],
       [ -3.00306720e-01,  -8.76237405e-02,   1.37220899e+00],
       [ -1.69309581e-09,  -2.91025082e-09,   1.61168440e+01]])

In [17]:
def shiftQR(A,eps):
    A=linear.hessenberg(A)
    eigenvalues=[]
    while(len(A)>1):
        A=shiftQRStep(A,eps)
        eigenvalues.append(A[-1,-1])
        A=A[:-1,:-1]
    eigenvalues.append(A[0,0])
    return eigenvalues

In [18]:
shiftQR(A,10**-10)

[-1.1491041660185517e-15, -1.1168439698070547, 16.116843969807057]