In [46]:
from eigenvalues import *

In [2]:
import numpy as np
import scipy.linalg as linear

In [3]:
import imp

In [4]:
imp.reload(eigenvalues)

<module 'eigenvalues' from 'eigenvalues.pyc'>

In [324]:
def SVD(A, tol=1e-7):
    '''
    Given a matrix A, return its Singular Value Decomposition. That is, A i
    
    and reducing the dimension of A to (M-1,M-1) until A becomes a single number.
    This algorithm converges to an upper triangle matrix with the eigenvalues of A in the diagonal. If A is symmetric, the Q matrices of each iteration can be accumulated to approximate the normal eigenvectors
    
    Parameters
    ----------
    A : (M, N) double ndarray
        A real matrix whose SVD will be calculated.
    tol : double, optional
         Cutoff point that determines 'important' singular values. Default is 1e-7.
        
    Returns
    -------
    U : (M, k) double ndarray
        A unitary matrix that contains the first k left singular vectors of A.
    S : (k, k) double ndarray
        A square real diagonal matrix whose elements are the k singular values of A greater that the tolerance. 
    V : (k, N) 
        A unitary matrix that contains the first k right singular vectors of A.
    '''
    rows, cols = A.shape
    if rows > cols: # Method procedes with lower rank matrix between AA* and A*A
        L, U, _ = shiftQR(np.dot(A,A.T), symmetric=True)
    else:
        L, V, _ = shiftQR(np.dot(A.T,A), symmetric = True)
    
    singularValues = [x**0.5 for x in L] # The singular values of A are the square root of the eigenvalues returned
    k = 0
    while k < len(singularValues) and singularValues[k] > tol: # Determine cutoff point 
        k+=1
        
    S = np.diag(singularValues[:k])
    
    if rows > cols: # Calculate remaining singular vectors depending on path chosen at the beginning
        U = U[:,:k]
        V = np.array([1/singularValues[i]*A.T.dot(U[:,i]) for i in range(k)]).T
    else:
        V = V[:,:k]
        U = np.array([1/singularValues[i]*A.dot(V[:,i]) for i in range(k)]).T
    return U, S, V

In [347]:
A = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [348]:
u,s,v = SVD(A)

In [349]:
s

array([[  2.54624074e+01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.29066168e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.03783221e-07]])

In [342]:
u.dot(s).dot(v.T)

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [343]:
B = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [344]:
u,s,v = SVD(B)

/Users/alex/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:30: RuntimeWarning: invalid value encountered in double_scalars


In [345]:
s

array([[  2.54368356e+01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.72261225e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.16993518e-07]])

In [346]:
u.dot(s).dot(v.T)

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])