In [37]:
import sys
sys.path.append('../')
from IPython.display import Latex
import latexStrings as ls
import numpy as np
import scipy.linalg as linear
from eigenvalues import *

# Ejercicio 6

Comparación de los resultados (errores en eigenvalores) entre la implementación del método QR simple y los del QR con shifts dinámicos con el resultado la librería linalg. 

Considerémos la matriz de fiedler(25)
Le aplicaremos el método de QR simple con un máximo de 2000 iteraciones, y el de QR con shift dinámico con un máximo de 20 iteraciones. En ambos casos la tolerancia será de 1e-10

In [112]:
QR_eig, QR_iter = simpleQR(fiedler(25), maxIter=2000, tol=1e-10)
shQR_eig, shQR_iter = shiftQR(fiedler(25), maxIter=20, tol=1e-10)
actual = linear.eig(fiedler(25))[0].real
err_abs_QR = abs(QR_eig - actual)
err_abs_shQR = abs(shQR_eig - actual)
err_rel_QR = abs((QR_eig - actual) / actual)
err_rel_shQR = abs((shQR_eig - actual) / actual)

Comparando los dos...

**Error absoluto:**

In [113]:
err_abs_QR, err_abs_shQR

(array([6.25277607e-13, 1.27897692e-13, 2.84217094e-14, 8.88178420e-15,
        5.68434189e-14, 8.88178420e-15, 7.54951657e-15, 4.44089210e-15,
        3.99680289e-15, 1.11022302e-15, 6.43929354e-15, 1.77635684e-15,
        5.77315973e-15, 6.66133815e-16, 8.88178420e-16, 5.55111512e-15,
        5.55111512e-16, 4.44089210e-16, 6.66133815e-16, 5.55111512e-16,
        5.55111512e-16, 2.33146835e-15, 1.88737914e-15, 5.99405459e-03,
        5.99405459e-03]),
 array([1.37144184e-07, 1.37143942e-07, 3.55271368e-14, 2.88221180e-09,
        3.78783760e-09, 1.13858408e-06, 3.78995463e-07, 1.09361161e-05,
        1.06148108e-08, 1.72948440e-05, 7.22173454e-06, 2.95257115e-06,
        1.31078567e-05, 6.32192284e-06, 5.27355225e-06, 7.93329256e-07,
        7.77156117e-16, 1.22124533e-15, 1.66533454e-15, 9.99200722e-16,
        2.22044605e-16, 4.44089210e-16, 1.11022302e-16, 5.99405459e-03,
        5.99405459e-03]))

**Error relativo:**

In [114]:
err_rel_QR, err_rel_shQR

(array([2.88502741e-15, 1.00851151e-15, 7.10007436e-16, 6.23710098e-16,
        6.68760056e-15, 1.69626984e-15, 2.00421377e-15, 1.61016094e-15,
        1.83550114e-15, 6.37513052e-16, 4.42239050e-15, 1.44350076e-15,
        5.39097271e-15, 7.07960703e-16, 1.05229088e-15, 7.26650403e-15,
        7.90443914e-16, 6.82044108e-16, 1.08996871e-15, 9.59770390e-16,
        1.00386608e-15, 4.37454964e-15, 3.64179474e-15, 1.19406927e-02,
        1.17997949e-02]),
 array([6.32782505e-10, 1.08142095e-09, 8.87509295e-16, 2.02399041e-10,
        4.45637250e-10, 2.17450210e-07, 1.00614115e-07, 3.96517335e-06,
        4.87477063e-09, 9.93105756e-06, 4.95975685e-06, 2.39931449e-06,
        1.22401079e-05, 6.71887965e-06, 6.24796866e-06, 1.03848148e-06,
        1.10662148e-15, 1.87562130e-15, 2.72492177e-15, 1.72758670e-15,
        4.01546432e-16, 8.33247551e-16, 2.14223220e-16, 1.19406927e-02,
        1.17997949e-02]))

Es algo dificil comparar 25 número a la vez, así que para darnos una mejor idea de lo que pasa, compararemos la norma de los vectores de error

In [115]:
Latex('QR simple: $\quad\epsilon_{abs} = $ ' + str(linear.norm(err_abs_QR)))

<IPython.core.display.Latex object>

In [116]:
Latex('QR con shift dinámico: $\quad\epsilon_{abs} = $ ' + str(linear.norm(err_abs_shQR)))

<IPython.core.display.Latex object>

In [117]:
Latex('QR simple: $\quad\epsilon_{rel} = $ ' + str(linear.norm(err_rel_QR)))

<IPython.core.display.Latex object>

In [118]:
Latex('QR con shift dinámico: $\quad\epsilon_{rel} =$ ' + str(linear.norm(err_rel_shQR)))

<IPython.core.display.Latex object>

Nótese que en ambos casos el método de QR simple logra una mejor aproximación. Pero vemos que...

In [119]:
QR_iter, shQR_iter

(1571, 20)

El método de QR simple hace casi 800 veces el número de iteraciones que el QR con shift! y aún así ambas aproximaciones son bastante buenas.

Veamos que pasa si limitamos el método de QR simple a 20 iteraciones...

In [120]:
QR_eig, QR_iter = simpleQR(fiedler(25), maxIter=20, tol=1e-10)
err_abs_QR = abs(QR_eig - actual)
err_rel_QR = abs((QR_eig - actual) / actual)

In [121]:
Latex('QR simple: $\quad\epsilon_{abs} = $ ' + str(linear.norm(err_abs_QR)))

<IPython.core.display.Latex object>

In [122]:
Latex('QR con shift dinámico: $\quad\epsilon_{abs} = $ ' + str(linear.norm(err_abs_shQR)))

<IPython.core.display.Latex object>

In [123]:
Latex('QR simple: $\quad\epsilon_{rel} = $ ' + str(linear.norm(err_rel_QR)))

<IPython.core.display.Latex object>

In [124]:
Latex('QR con shift dinámico: $\quad\epsilon_{rel} =$ ' + str(linear.norm(err_rel_shQR)))

<IPython.core.display.Latex object>

Nótese que el error absoluto ahora el mucho mayor, y el error relativo es 10 mayor!

Si no limitamos el número de iteraciones, observamos que:

In [129]:
QR_eig, QR_iter = simpleQR(fiedler(25), maxIter=10000,  tol=1e-10)
shQR_eig, shQR_iter = shiftQR(fiedler(25), tol=1e-10)
err_rel_QR = abs((QR_eig - actual) / actual)
err_rel_shQR = abs((shQR_eig - actual) / actual)

In [130]:
Latex('QR simple: $\quad\epsilon_{rel} = $ ' + str(linear.norm(err_rel_QR)))

<IPython.core.display.Latex object>

In [131]:
Latex('QR con shift dinámico: $\quad\epsilon_{rel} =$ ' + str(linear.norm(err_rel_shQR)))

<IPython.core.display.Latex object>

Para fines prácticos, el error relativo el el mismo

In [132]:
QR_iter, shQR_iter

(1571, 38)

In [133]:
QR_iter/shQR_iter

41.3421052631579

Pero el método de QR simple hace más de 40 veces el número de iteraciones!