In [48]:
import sys
sys.path.append('../')
from IPython.display import Latex
import latexStrings as ls
import numpy as np
import scipy.linalg as linear
import eigenvalues as ev

# Ejercicio 2.2.1

Utilizando la matriz $A$ y el vector $q_0$ del ejercicio anterior definidos como sigue:

In [49]:
A = np.array([[1,1,2],[-1,9,3],[0,-1,3]])
q = np.array([1,1,1])

Latex(ls.latexMatrix(A,'A') + ls.latexVector(q,'q_0'))

<IPython.core.display.Latex object>

Se calcularán 10 iteraciones del método de la potencia con $shift$ $\rho_1$ y $\rho_2$ y donde $q_{10}$ es el vector que se aporxima al eigenvector y $\sigma_{10}$ el eigenvalor aproximado después de 10 iteraciones.


Para $\rho_1=0$, que es simplemente aplicar el método de la potencia inversa, se obtiene:

In [50]:
[q10, l10 ,iterations]=ev.inversePowerShift(A,q,0,1e-6,10)
print('Numero de Iteraciones: ' + str(iterations))
Latex(ls.latexVector(q10,'q_{10}', form='%f') + '$$\sigma_{10} = '+str(l10)+'$$')

Numero de Iteraciones: 10


<IPython.core.display.Latex object>

Comparando los resultados anteriores con los valores 'exactos' calculados por el paquete 'linalg' de 'scipy':

In [51]:
[L,V] = linear.eig(A)
Latex(ls.latexVector(L,'\lambda',form='%f') + ls.latexMatrix(V,'V',form='%f'))


<IPython.core.display.Latex object>

$\overrightarrow{\lambda}$ es el vector que contiene a los tres eigenvalores "exactos" de la matriz $A$ y las columnas de la matriz $V$ son los eigenvectores "exactos"de $A$.

Se observa que $\sigma_{10}=1.22678942614$ tiene dos decimales iguales a $\lambda_{2}=1.224672$ , la segunda entrada de $\overrightarrow{\lambda}$. Dado que el método converge teóricamente al eigenpar dominante en este caso 

De la matriz $V$ tomamos $\overrightarrow{v_2}$, el eigenvector asignado a $\lambda_2$, y lo comparamos con $\overrightarrow{q_{10}}$

In [52]:
v=V[:,1]
Latex(ls.latexVector(v, 'v_2', form='%f')+ls.latexVector(q10,'q_{10}', form='%f'))


<IPython.core.display.Latex object>

In [53]:
v=-v

Observamos que $\overrightarrow{q_{10}}$ es apximadamente $-\overrightarrow{v_2}$, entonces de ahora en adelante nos referiremos a $\overrightarrow{v_2}$ por  el valor de $-\overrightarrow{v_2}$:

In [54]:
Latex(ls.latexVector(v, 'v_2', form='%f'))

<IPython.core.display.Latex object>

Calculando las razones de convergencia en cada paso de la iteracion, dadas por:
$$ r_i = \frac{\Vert q_{i}-v \Vert_\infty}{\Vert q_{i-1}-v \Vert_\infty} \qquad i\in \{1,2,...,10\} $$
Para luego poder comparar esto con la razon de convergencia teórica, dada por:
$$ r = \left| \frac{\lambda_2}{\lambda_3} \right| = 0.35800909831776 $$
donde: $$|\lambda_2|<|\lambda_3|<|\lambda_1| \Rightarrow |\lambda_2|^{-1}>|\lambda_3|^{-1}>|\lambda_1|^{-1}$$


In [55]:
ratios=[]
prevq=q
for i in range(1,10):
    [currentq,_,_] = ev.inversePowerShift(A,q,0,1e-6,i)
    ratio = linear.norm(currentq-v,np.inf)/linear.norm(prevq-v,np.inf)
    ratios.append(ratio)
    prevq = currentq
Latex(ls.latexList(ratios,'\widetilde{r}', form='%f'))

<IPython.core.display.Latex object>

Donde $\widetilde{r}$ es el arreglo cuyo elemento $i$ es la razón de la iteración $i$ con $i\in \{1,2,...,10\}$.

Se oberva que el elemento 10 de $\widetilde{r}$ es $0.359880$ que aproximademente la razón teórica $r=0.35800909831776$

# Ejercicio 2.2.2

Para la misma matriz $A$ y vector $q_0$ defininidos anteriormente, se realizarán las mismas pruebas para un $shift$ $\rho_2=3.3$. Se encontrará un vector $\overrightarrow{\tilde{q_{10}}}$, la aproximación de eigenvector, y $\tilde{\sigma_{10}}$ la aproximación del eigenvalor.

In [56]:
[q10, l10 ,iterations]=ev.inversePowerShift(A,q,3.3,1e-6,10)
print('Numero de Iteraciones: ' + str(iterations))
Latex(ls.latexVector(q10,'q_{10}', form='%f') + '$$\sigma_{10} = '+str(l10)+'$$')

Numero de Iteraciones: 4


<IPython.core.display.Latex object>

La primera observación es que el proceso sólo hizo 4 iteraciones, esto quiere decir que el método alcanzó el citerio de error relativo sin necesidad de hacer las 10 iteraciones. Comparemos los resultados anteriores con los valores 'exactos' calculados por el paquete 'linalg' de 'scipy':

In [57]:
[L,V] = linear.eig(A)
Latex(ls.latexVector(L,'\lambda',form='%f') + ls.latexMatrix(V,'V',form='%f'))



<IPython.core.display.Latex object>

El vector $\overrightarrow{q_{10}}$ es igual al eigenvector "exacto" $\overrightarrow{v_{3}}$, tercera columna de la matriz $V$. El valor $\sigma_{10}$  tiene 5 cifras decimales iguales al eigenvalor "exacto" $\lambda_3$, tercera entrada del vector $\overrightarrow{\lambda}$.

Calculando las razones de convergencia en cada paso de la iteracion, dadas por:
$$ r_i = \frac{\Vert q_{i}-v \Vert_\infty}{\Vert q_{i-1}-v \Vert_\infty} \qquad i\in \{1,2,...,10\} $$
Para luego poder comparar esto con la razon de convergencia teórica, dada por:
$$ r = \left| \frac{\lambda_3-\rho_2}{\lambda_2-\rho_2} \right| = 0.05819972269618957 $$
donde: $$|\lambda_3-\rho_2|<|\lambda_2-\rho_2|<|\lambda_1-\rho_2| \Rightarrow |\lambda_3-\rho_2|^{-1}>|\lambda_2-\rho_2|^{-1}>|\lambda_1-\rho_2|^{-1}$$



In [58]:
abs((L[2]-3.3)/(L[1]-3.3))

0.05819972269618957

In [66]:
ratios=[]
v=V[:,2]

prevq=q
for i in range(1,11):
    [currentq,_,_] = ev.inversePowerShift(A,q,3.3,-1,i)
    print (currentq)
    ratio = linear.norm(currentq-v,np.inf)/linear.norm(prevq-v,np.inf)
    ratios.append(ratio)
    prevq = currentq
Latex(ls.latexList(ratios,'\widetilde{r}', form='%s'))

[ 0.52146768 -0.31311737  0.79374365]
[ 0.51552416 -0.33190623  0.78998297]
[ 0.51531203 -0.33237562  0.78992402]
[ 0.51531098 -0.33238529  0.78992064]
[ 0.51531072 -0.33238561  0.78992067]
[ 0.51531073 -0.33238561  0.78992067]
[ 0.51531073 -0.33238561  0.78992067]
[ 0.51531073 -0.33238561  0.78992067]
[ 0.51531073 -0.33238561  0.78992067]
[ 0.51531073 -0.33238561  0.78992067]


<IPython.core.display.Latex object>

Donde $\widetilde{r}$ es el arreglo cuyo elemento $i$ es la razón de la iteración $i$ con $i\in \{1,2,...,10\}$.